version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pgdb
    environment:
      POSTGRES_DB: rickmortydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seed:/docker-entrypoint-initdb.d    # Map the directory containing seed.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pgdata:
